apiVersion : "v1"
kind : "Deployment"
metadata:
    name:"devops-nagpTest-deployment"
    labels:
        app:"devops"
spec:
    replicaSet : 3
    selector:
        matchLabel:
            app:"devops"
    template:
        metadata:
            labels:
                name: "devops"
        spec:
            containers:
                name : "devops"
                image : "i_kunal_feature : latest"
                ports:
                    - containerPort:87124
                      name : "http"
                      protocol : 'TCP'
	
		
		
		
		
---
apiVersion: "v1"
kind : "Service"
metadata:
    name : "lbService"
spec:
    type:"LoadBalancer"
    selector:
        app : "devops"
    ports:
        targetPort: 87124
        Port : 80
	
	
