apiVersion : apps/v1
kind: Deployment
metadata:
    name: devops-app-deployment
    namespace: kubernetes-cluster-kunal
    labels:
        app: devops-app
spec:
    replicas: 4
    selector :
        matchLabels:
            app:devops-app
    template:
        metadata:
            labels:
                app: devops-app
spec:
    containers:
      - name: devops-app
        image: kunalnagarro/devops:master
        ports:
          - name: http
            containerPort : 80
            protocol : TCP
---
apiVersion: v1
kind: Service
metadata:
    name: devops-app
    namespace: kubernetes-cluster-kunal
spec:
    type: NodePort
    selector:
        app: devops-app
    ports:
      - protocol : TCP
        nodePort: 30158
        port: 80
        targetport: 80
