apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  namespace: namespace: kubernetes-cluster-kunal
  labels:
    app: devops
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops
        image: kunalnagarro/devops:master
        ports:
          - name: http
            containerPort: 80
            protocol: TCP

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: devops-deployment-service
  namespace: kubernetes-cluster-kunal
  labels:
    app: devops
spec:
  type: NodePort
  selector: 
    app: devops
  ports: 
  - protocol: "TCP"
    nodePort: 30157
    port: 80
    targetPort: 80
  selector: 
    app: devops
  type: "LoadBalancer"
